# Generated by Django 3.2.16 on 2023-04-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_booked',
            field=models.PositiveIntegerField(choices=[('WAITING', 'WAITING'), ('APPROVED', 'APPROVED')], default=0),
        ),
    ]
